// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Dinner Run",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Dinner Run",
            targets: ["AppModule"],
            bundleIdentifier: "com.StudentChallenge.DinnerRun",
            teamIdentifier: "TA9GQL43ZA",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)